name: Publish Post From Notion

on:
  workflow_dispatch:
    inputs:
      notion_page_id:
        description: 'Notion Page ID'
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler-cache: true
              
      - name: Import post from Notion
        env:
          NOTION_SECRET: ${{ secrets.NOTION_SECRET }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
        run: |
          bin/import_post_notion ${{ github.event.inputs.notion_page_id }}
        
      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "Add new post from Notion page ${{ github.event.inputs.notion_page_id }}"
          git push origin main
